### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by fuziwang** [skelemoa/ntu-x#2]
Please provide the download link of NTU60-X dataset, I will be very grateful!

**Comment by cvitatma** [comment]
Thanks for your interest in the NTU-X dataset. The rules for downloading NTU dataset mention that prior permission is required to release a new dataset derived from the original dataset. We are awaiting the permission. Once we receive the go ahead, we will be very happy to release/share the dataset. Thanks for your understanding.
