### ISSUE TITLE
Please Provide US Download Link of Data Set

### ISSUE THREAD

**Issue by MujahidRasool** [skelemoa/ntu-x#3]
HI, 

I want to download this data set and want to use it in my research. Can you provide me a link to this data set with 60 classes . Thanks

**Comment by Anirudh257** [comment]
@MujahidRasool Thanks for your interest. The rules for downloading the NTU dataset mention that prior permission is required to release a new dataset derived from the original dataset. We are awaiting your permission. Once we receive the go-ahead, we will be very happy to release/share the dataset. Thanks for your understanding.

**Comment by MujahidRasool** [comment]
I have the permission that is simple email and password. How Can I show you?

**Comment by Anirudh257** [comment]
The permission is for the original NTU dataset, not for our work, which is a **derivative of the original version**. We can't release our novel dataset until we get the required permissions.

**Comment by MujahidRasool** [comment]
Yes I have that on their NTU site

**Comment by MujahidRasool** [comment]
How can I show you that? Did you need Username and Password?
