### ISSUE TITLE
Download Dataset

### ISSUE THREAD

**Issue by sonwe1e** [skelemoa/ntu-x#5]
Could you tell me how to get this dataset or when do you release it?

**Comment by sankadivandya** [comment]
Yes please!

**Comment by Anirudh257** [comment]
We don't have the relevant permissions to release the dataset yet.

**Comment by fuziwang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
