### ISSUE TITLE
Release code for generating NTU-X

### ISSUE THREAD

**Issue by DSAureli** [skelemoa/ntu-x#6]
Hello,

thank you for you work, it seems very promising. I would like to use your dataset for my thesis project, but I see that you don't have the permission for publishing it yet. Would it be possible for you to at least publish the code you used for generating your dataset from the original NTU data, so that people having access to the original dataset can generate NTU-X themselves?

Thank you

**Comment by neel1998** [comment]
Hey apologies for late response. We have used the exact generation script as provided by [Smplify-X](https://github.com/vchoutas/smplify-x) and [ExPose](https://github.com/vchoutas/expose). You can easily follow their generation guidelines for the original dataset videos and generate the NTU-X data.

**Comment by DSAureli** [comment]
Got it, thanks.
