### ISSUE TITLE
OpenPose keypoints json files from NTU-60 and 120 for Smplify-X

### ISSUE THREAD

**Issue by DegardinBruno** [skelemoa/ntu-x#7]
Dear @Anirudh257, thank you very much for the excellent work!

I understand that you can not release the dataset itself of NTU-X.
However, could we get the OpenPose Keypoints json files from NTU-60 and NTU-120 videos that you used for Smplify-X (and others)?

This could facilitate the reproduction of NTU-X!

Thank you once again for your attention.

**Comment by fuziwang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Anirudh257** [comment]
Hi, we can't release the Openpose files either.
